### ISSUE TITLE
PackagesNotFoundError:   - python=3.8.5

### ISSUE THREAD

**Issue by elityy** [VideoCrafter/VideoCrafter#11]
When I am trying to create the env, I get the error: PackagesNotFoundError: ```
The following packages are not available from current channels:

  - python=3.8.
```
I am using MacOS, is it only for Linux systems?

**Comment by liulam123** [comment]
Run before execution : 

conda config --append channels conda-forge

**Comment by scutpaul** [comment]
Hi, we are currently adapting to macos, you can switch to this branch: https://github.com/VideoCrafter/VideoCrafter/tree/macos-branch
