### ISSUE TITLE
what  kind  of   gpu?that's most important

### ISSUE THREAD

**Issue by jackylee1** [VideoCrafter/VideoCrafter#15]
what  kind  of   gpu?that's most important

**Comment by seel-channel** [comment]
Probably at least 16 GB VRAM

**Comment by scutpaul** [comment]
Currently, our text2video model requires a minimum of 6.3GB of memory by using xformers. https://github.com/VideoCrafter/VideoCrafter/issues/3#issuecomment-1498604731
