### ISSUE TITLE
train

### ISSUE THREAD

**Issue by dlutzzw** [VideoCrafter/VideoCrafter#16]
Thank you very much for your excellent works. I don't seem to see the training code, how can I use the pre-trained t2v model to train my own videocontrol model?

**Comment by yzhang2016** [comment]
We will release some videocontrol models first. The training code of LoRA and videocontrol will be released later.

**Comment by dlutzzw** [comment]
ok, thanks!



---- Replied Message ----
| From | ***@***.***> |
| Date | 04/10/2023 12:38 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [VideoCrafter/VideoCrafter] train (Issue #16) |

We will release some videocontrol models first. The training code of LoRA and videocontrol will be released later.

**Comment by dlutzzw** [comment]
hi, May I ask when will this part of the code be open sourced? Is there an approximate time?

**Comment by ryx19th** [comment]
Hi I'm also interested in this part. May I ask if you'd have any plan so far? Thank you very much!

**Comment by howardgriffin** [comment]
Waiting for the training code too.

**Comment by caojiehui** [comment]
The training code......

**Comment by djh123** [comment]
The training code......
