### ISSUE TITLE
Collab

### ISSUE THREAD

**Issue by Niutonian** [VideoCrafter/VideoCrafter#3]
Fantastic work, do you plan on releasing a collaborator by any chance?

What are the GPU requirements, can I run from a 8gb card? Thanks

**Comment by YingqingHe** [comment]
Hi, thanks for your interest! We are still working on the Huggingface Gradio demo and also Colab. They will release in a few days. For the GPU requirements, it currently needs more than 9 GB of GPU memory. We are also working on saving GPU memory costs now.

**Comment by scutpaul** [comment]
Hi, we just update the xformer requirement. Thanks to xformer, our GPU memory usage is around 6.3GB.

**Comment by Niutonian** [comment]
Hello thanks for the quick update, I will give it a try now

**Comment by vinthony** [comment]
update colab and hugging face demo.
