### ISSUE TITLE
about  long  video

### ISSUE THREAD

**Issue by zhanghongyong123456** [VideoCrafter/VideoCrafter#4]
Thank you very much for your excellent works. I see that more than one thousand frames of video can be generated. How to set this, my test only has 16 frames of video

**Comment by YingqingHe** [comment]
Hi, for text-to-video generation, we offer a model that generates only 16-frame videos🤠.

**Comment by LinghaoChan** [comment]
Can it not generate long videos so far?

**Comment by MuDong612** [comment]
I want to generate more frames too，but if I set frame上 more than 16，the resulting video will be terrible
