### ISSUE TITLE
pretrained T2V models download link not working anymore: quota exceeded

### ISSUE THREAD

**Issue by AugmentedRealityCat** [VideoCrafter/VideoCrafter#5]
The link you provide to download the T2V model is not working anymore. When you try to download the file, Google tells you this:
```
Sorry, you can't view or download this file at this time.

Too many users have viewed or downloaded this file recently. Please try accessing the file again later. If the file you are trying to access is particularly large or is shared with many people, it may take up to 24 hours to be able to view or download the file. If you still can't access a file after 24 hours, contact your domain administrator.
```
The link that does not work anymore: https://drive.google.com/file/d/13ZZTXyAKM3x0tObRQOQWdtnrI2ARWYf_/view?usp=share_link

I checked and most of the links you are providing for other models are also exceeding their download quota - the message I get when trying to download the LoRa models is this (can't copy the text, so it's a screenshot)
![Untitled-1](https://user-images.githubusercontent.com/114955776/230265315-5fcf075c-0146-465c-8278-d78b05b993a8.png)

**Comment by YingqingHe** [comment]
Hi, we are solving this issue now. Please wait a moment.

**Comment by YingqingHe** [comment]
Hi, you can try this link to download models: https://huggingface.co/VideoCrafter/t2v-version-1-1/tree/main/models

**Comment by AugmentedRealityCat** [comment]
The new links are working, thanks a lot for fixing this so quickly !
