### ISSUE TITLE
Running sample script

### ISSUE THREAD

**Issue by mischaschaub** [VideoCrafter/VideoCrafter#7]
Just installed everything according to your setup. When I try to run the sample script I get the attached errors. So what am I doing wrong? Many thanks
[error.txt](https://github.com/VideoCrafter/VideoCrafter/files/11168238/error.txt)

**Comment by vinthony** [comment]
Our script is written based on Linux, it can not directly works in Windows.

**Comment by mischaschaub** [comment]
OH, thanks for the  info.  Are you thinking of  porting your  solution to windows?
